announce = false
debug = true
description = 're:LIFE Development Server'
gamemode = 'Freeroam'
host = '0.0.0.0'
language = 'en'
modules = [ 'csharp-module' ]
name = 're:Life Development Server'
players = 128
port = 7788
resources = [ 'relife' ]
timeout = 1000
website = 'example.com'

[csharp-module]
disableDependencyDownload = true
